version: '3.8'
services:
  auth-service:
    container_name: auth
    build:
      dockerfile: Dockerfile.dev
      context: ./auth-service
    volumes:
        - ./volumes/auth:/app
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      JWT_TOKEN: ${JWT_TOKEN}
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app_network
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - app_network
    command: -p ${PG_PORT}


networks:
  app_network: 
   driver: bridge