version: '3.8'
services:
  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
      target: production
      context: ./auth-service
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      APP_PORT: ${APP_PORT}
      JWT_TOKEN: ${JWT_TOKEN}
      SWAGGER_USER: ${SWAGGER_USER}
      SWAGGER_PASSWORD: ${SWAGGER_PASSWORD}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - /github_actions/volumes/postgres:/var/lib/postgresql/data
    command: -p ${PG_PORT}

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./conf.d:/etc/nginx/conf.d
    depends_on:
        - auth-service
    
  web-launcher:
    container_name: web-launcher
    build:
      context: ./web-launcher
    ports:
      - "3000:4000"