version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: -p ${PG_PORT}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data