name: Deploy auth service

on:
  push:
    branches:
      - 'main'

jobs:
  auth-service:
    runs-on: self-hosted
    needs: [clone-repository]
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          rm -f .env
          touch .env
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Build services
        run: docker compose up -d --build
      - name: Status
        run: docker ps -a
