name: Deploy auth service

on:
  push:
    branches:
      - 'main'

jobs:
  auth-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          touch .env
          echo API_KEY=${{ secrets.ENV_FILE }} >> .env
      - name: Build services
        run: docker compose up -d --build auth
      - name: Status
        run: docker ps -a
