name: Deploy auth service

on:
  push:
    branches:
      - 'main'

jobs:
  auth-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          rm -f .env
          touch .env
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Stop services
        run: docker compose down
      - name: Pull services
        run: docker compose pull
      - name: Build services
        run: docker compose build
      - name: Run auth
        run: docker run -d -p 4000:4000 auth-service
      - name: Run bd
        run: docker run -d -p 5432:5432 auth-service
      - name: Status
        run: docker ps -a
