name: Deploy auth service

on:
  push:
    branches:
      - 'main'

jobs:
  init:
    name: Check changed files
    outputs:
      auth_service: ${{ steps.check_files.outputs.auth_service }}
      web_launcher: ${{ steps.check_files.outputs.web_launcher }}
      nginx: ${{ steps.check_files.outputs.nginx }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: check modified files
        id: check_files
        run: |
            git diff --name-only HEAD^ HEAD
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == auth-service/* ]]; then
                echo "::set-output name=auth_service::true"
              elif [[ $file == web-launcher/* ]]; then
                echo "::set-output name=web_launcher::true"
              elif [[ $file == conf.d/* ]]; then
                echo "::set-output name=nginx::true"
              else
                echo "file does not belong to any service"
              fi
            done < files.txt

  auth-service:
    runs-on: self-hosted
    needs: init
    # if: needs.check.outputs.auth_service == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          rm -f .env
          touch .env
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Run auth service
        run: docker compose up -d --build auth-service
      - name: Status
        run: docker ps -a

  web-service:
    runs-on: self-hosted
    needs: init
    # if: needs.check.outputs.web_launcher == 'true'
    steps:
      - name: Create env file
        run: |
          rm -f ./web-launcher/.env
          touch ./web-launcher/.env
          echo "${{secrets.WEB_ENV_FILE}}" > ./web-launcher/.env
      - name: Run web launcher
        run: docker compose up -d --build web-launcher
  
  nginx:
    runs-on: self-hosted
    needs: init
    # if: needs.check.outputs.nginx == 'true'
    steps:
      - name: Run nginx
        run: docker compose up -d --build nginx
    