name: Deploy auth service

on:
  push:
    branches:
      - 'main'

jobs:
  auth-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          rm -f .env
          touch .env
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Stop services
        run: docker compose stop
      # - name: Pull services
        # run: docker compose pull
      - name: Build services
        run: docker compose build
      - name: Run services
        run: docker compose up -d
      - name: Status
        run: docker ps -a
